"""RDKE home-page generator."""
from build import ROOT, cards, esc, grouped_cards, hero, load, shell


def build_home() -> None:
    content = load("home-content.json")
    components = load("components.json")
    northbound = load("northbound-apis.json")
    southbound = load("southbound-apis.json")
    body = hero("", content["title"], content["description"], content["badges"])
    title_html = '<h1 style="font-size:clamp(1.9rem,3.6vw,3.5rem)">' + esc(content["title"]) + '</h1>'
    subtitle_html = f'<div class="hero-subtitle" style="font-size:.95rem;font-weight:600;line-height:1;color:#b8df63;margin:0">{esc(content["eyebrow"])}</div>'
    intro_html = f'<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px;line-height:1"><div style="display:inline-flex;align-items:center;padding:5px 12px;border:1px solid #b8df63;border-radius:999px;color:#b8df63;font:700 .72rem/1 Consolas,monospace;letter-spacing:.14em">RDKE</div>{subtitle_html}</div>'
    body = body.replace(title_html, intro_html + title_html, 1)
    why = content["why"]
    body += f'''<section class="section"><div class="eyebrow">Why RDKE</div><h2>{esc(why["title"])}</h2><p class="lede">{esc(why["description"])}</p>{cards(why["cards"])}</section>'''
    architecture = content["architecture"]
    body += f'''<section class="section alt"><div class="eyebrow">Architecture</div><h2>RDKE architecture</h2><div style="display:grid;gap:0;max-width:1000px">{''.join(f'<article class="card" style="border-left-color:{color};border-radius:0"><h3>{esc(layer[0])}</h3><p>{esc(layer[1])}</p></article>' for layer, color in zip(why["cards"][:3], ("#29b6e8", "#7ac943", "#f5a623")))}</div></section>'''
    body += f'''<section class="section alt"><div style="display:flex;align-items:end;justify-content:space-between;gap:20px;flex-wrap:wrap;max-width:1080px"><div><div class="eyebrow">Core RDK platform</div><h2>Explore the registry</h2><p class="lede" style="margin-bottom:0">Review the platform building blocks, interfaces, and hardware references in one place.</p></div><span style="color:#5b6472;font:600 .72rem/1 Consolas,monospace;letter-spacing:.08em">REGISTRY INDEX</span></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px;max-width:1080px;margin-top:28px"><a href="component-registry.html" style="display:flex;flex-direction:column;justify-content:space-between;min-height:150px;padding:22px;text-decoration:none;color:inherit;background:#fff;border:1px solid var(--border);border-top:4px solid #29b6e8"><span style="color:#5b6472;font:700 .7rem/1 Consolas,monospace;letter-spacing:.1em">01 / COMPONENTS</span><strong style="font-size:2.8rem;color:#2457d6">{len(components.get("components", []))}</strong><span style="color:#5b6472">Core RDK components <b style="float:right;color:#2457d6">↗</b></span></a><a href="southbound-apis.html" style="display:flex;flex-direction:column;justify-content:space-between;min-height:150px;padding:22px;text-decoration:none;color:inherit;background:#fff;border:1px solid var(--border);border-top:4px solid #7ac943"><span style="color:#5b6472;font:700 .7rem/1 Consolas,monospace;letter-spacing:.1em">02 / SOUTHBOUND</span><strong style="font-size:2.8rem;color:#2457d6">{len(southbound.get("apis", []))}</strong><span style="color:#5b6472">HAL interfaces <b style="float:right;color:#2457d6">↗</b></span></a><a href="northbound-apis.html" style="display:flex;flex-direction:column;justify-content:space-between;min-height:150px;padding:22px;text-decoration:none;color:inherit;background:#fff;border:1px solid var(--border);border-top:4px solid #f5a623"><span style="color:#5b6472;font:700 .7rem/1 Consolas,monospace;letter-spacing:.1em">03 / NORTHBOUND</span><strong style="font-size:2.8rem;color:#2457d6">{len(northbound.get("apis", []))}</strong><span style="color:#5b6472">API entries <b style="float:right;color:#2457d6">↗</b></span></a></div></section>'''
    body = body.replace("Explore the registry", "Explore the Core RDK platform").replace("Review the platform building blocks, interfaces, and hardware references in one place.", "Explore the platform building blocks and standardized interfaces connecting applications, middleware, and the vendor layer.").replace("REGISTRY INDEX", "")
    body = body.replace('<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px;max-width:1080px;margin-top:28px">', '<style>.rdk-platform-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px;max-width:1080px;margin-top:28px}.rdk-platform-cards a{min-height:170px!important;padding:22px!important;border:1px solid var(--border)!important;border-top:4px solid var(--rdk-blue)!important;border-radius:8px;box-shadow:var(--shadow);transition:transform .15s,box-shadow .15s}.rdk-platform-cards a:nth-child(2){border-top-color:var(--rdk-green)!important}.rdk-platform-cards a:nth-child(3){border-top-color:var(--rdk-amber)!important}.rdk-platform-cards a:hover{transform:translateY(-2px);box-shadow:0 12px 28px #0b122022}</style><div class="rdk-platform-cards">', 1)
    footer = "Copyright © 2026 RDK Management, LLC"
    (ROOT / "index.html").write_text(shell("RDKE. Core RDK Entertainment Platform", "home", body, footer), encoding="utf-8")

if __name__ == "__main__":
    build_home()
